"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = "\uf662 "
force_display = true

[azure]
symbol = "\ufd03 "
disabled = false

[c]
symbol = "\ue61d "

[conda]
symbol = "\uf10c "

[cmd_duration]
min_time = 500

[dart]
symbol = "\ue798 "

[directory]
read_only = " \uf83d "

[docker_context]
symbol = "\uf308 "

[dotnet]
symbol = "\uf81a "

[elixir]
symbol = "\ue62d "

[elm]
symbol = "\ue62c "

[erlang]
symbol = "\ue7b1 "

[gcloud]
symbol = "\ue7b2 "

[git_branch]
symbol = "\ue725 "

[git_commit]
tag_symbol = "\uf02b "
tag_disabled = false

[git_metrics]
disabled = false

[golang]
symbol = "\ue724 "

[haskell]
symbol = "\ue777 "

[hostname]
ssh_only = true
ssh_symbol = "\ueb01 "

[hg_branch]
symbol = "\ue725 "

[java]
symbol = "\ue738 "

[julia]
symbol = "\ue624 "

[kotlin]
symbol = "\ue634 "

[kubernetes]
symbol = "\ufd31 "
disabled = false

[lua]
symbol = "\ue620 "

[memory_usage]
symbol = "\uf85a "
disabled = false

[meson]
symbol = "\ufa36 "

[nim]
symbol = "\uf6a4 "

[nix_shell]
symbol = "\uf2dc "

[nodejs]
symbol = "\ue719 "

[openstack]
symbol = "\ue771 "

[package]
symbol = "\uf8d6 "

[php]
symbol = "\ue76e "

[python]
symbol = "\ue235 "
style = "green bold"

[rlang]
symbol = "ﳒ "

[ruby]
symbol = "\ue791 "

[rust]
symbol = "\ue7a8 "

[scala]
symbol = "\ue737 "

[shell]
zsh_indicator = "\uf79f"
style = "green bold"
disabled = false

[status]
symbol = "\uf467 "
success_symbol = ""
not_executable_symbol = "\uebd6 "
map_symbol = false
disabled = false

[swift]
symbol = "\ue755 "

[terraform]
symbol = "\ufa08 "
