default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-docstring-first
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.3.3
    hooks:
      - id: validate_manifest
