# == Fonts ==
cask "sf-symbols"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-space-mono-nerd-font"
cask "font-symbols-only-nerd-font"

# == Applications ==
cask "aerospace"
cask "cursor"
cask "dbeaver-community"
cask "docker"
cask "flux"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "mongodb-compass"
cask "nordpass"
cask "nordvpn"
cask "notesnook"
cask "obsidian"
cask "raycast"
cask "spotify"
cask "telegram"
cask "vesktop"
cask "visual-studio-code"
cask "zed"
cask "zen-browser"

# == Programming languages ==
brew "elixir"
brew "erlang"
brew "gcc"
brew "gleam"
brew "lua"
brew "rust"
brew "rustup"
brew "uv"

# == Databases ==
brew "duckdb"

# == Command-line tools ==
brew "bat"
brew "bottom"
brew "curl"
brew "exercism"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "fish"
brew "git-delta"
brew "git-lfs"
brew "gh"
brew "gnupg"
brew "graphviz"
brew "helix"
brew "jq"
brew "k9s"
brew "lazydocker"
brew "lazygit"
brew "pinentry-mac"
brew "minikube"
brew "ripgrep"
brew "spicetify-cli"
brew "starship"
brew "vhs"
brew "wget"
brew "yazi"
brew "zellij"
brew "zoxide"

# == Language server protocols ==
brew "marksman"
brew "taplo"
brew "yaml-language-server"

# == Taps ==
tap "FelixKratz/formulae"
brew "borders"
