# == Fonts ==
cask "sf-symbols"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-space-mono-nerd-font"
cask "font-symbols-only-nerd-font"

# == Applications ==
cask "aerospace"
cask "cursor"
cask "dbeaver-community"
cask "docker"
cask "flux"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "maccy"
cask "mongodb-compass"
cask "nordpass"
cask "nordvpn"
cask "obsidian"
cask "raycast"
cask "spotify"
cask "telegram"
cask "vesktop"
cask "visual-studio-code"
cask "zed"
cask "zen-browser"

# == Programming languages ==
brew "elixir"
brew "erlang"
brew "gcc"
brew "gleam"
brew "lua"
brew "rust"
brew "rustup"
brew "uv"

# == Databases ==
brew "duckdb"

# == Command-line tools ==
brew "bat"
brew "bottom"
brew "curl"
brew "exercism"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "fish"
brew "git-delta"
brew "git-lfs"
brew "gh"
brew "gnupg"
brew "graphviz"
brew "helix"
brew "jq"
brew "k9s"
brew "lazydocker"
brew "lazygit"
brew "pinentry-mac"
brew "minikube"
brew "ripgrep"
brew "spicetify-cli"
brew "starship"
brew "vhs"
brew "wget"
brew "yazi"
brew "zellij"
brew "zoxide"

# == Language server protocols ==
brew "marksman"
brew "taplo"
brew "yaml-language-server"

# == Taps ==
tap "FelixKratz/formulae"
brew "borders"

# == VSCode ==
vscode "arr.marksman"
vscode "catppuccin.catppuccin-vsc"
vscode "charliermarsh.ruff"
vscode "dorzey.vscode-sqlfluff"
vscode "dustypomerleau.rust-syntax"
vscode "editorconfig.editorconfig"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "gleam.gleam"
vscode "kend.dancehelixkey"
vscode "matangover.mypy"
vscode "miguelsolorio.fluent-icons"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "robertostermann.inline-parameters-extended"
vscode "rust-lang.rust-analyzer"
vscode "samuelcolvin.jinjahtml"
vscode "tamasfe.even-better-toml"
vscode "yzhang.markdown-all-in-one"
