# == Taps ==
tap "catppuccin/tap"

# == Fonts ==
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-space-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "sf-symbols"

# == Applications ==
cask "dbeaver-community"
cask "docker-desktop"
cask "flux-app"
cask "ghostty"
cask "insomnia"
cask "karabiner-elements"
cask "maccy"
cask "mongodb-compass"
cask "nordpass"
cask "nordvpn"
cask "obsidian"
cask "rectangle"
cask "spotify"
cask "telegram"
cask "vesktop"
cask "visual-studio-code"
cask "zed"
cask "zen"

# == Programming languages ==
brew "elixir"
brew "erlang"
brew "gcc"
brew "gleam"
brew "lua"
brew "rust"

# == Package managers ==
brew "rustup"
brew "uv"
brew "poetry"

# == Databases ==
brew "duckdb"

# == Command-line tools ==
brew "bat"
brew "bottom"
brew "copilot"
brew "curl"
brew "docker-clean"
brew "exercism"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "gnupg"
brew "graphviz"
brew "helix"
brew "hyperfine"
brew "jq"
brew "just"
brew "k9s"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "maturin"
brew "minikube"
brew "pinentry-mac"
brew "pyenv"
brew "ripgrep"
brew "spicetify-cli"
brew "starship"
brew "vhs"
brew "wget"
brew "whalebrew"
brew "whiskers"
brew "yazi"
brew "zellij"
brew "zoxide"

# == Language server protocols ==
brew "elixir-ls"
brew "marksman"
brew "taplo"
brew "yaml-language-server"

# == Python packages ==
brew "mypy"
brew "pyupgrade"
brew "ruff"
brew "sqlfluff"

# == VSCode extensions ==
vscode "catppuccin.catppuccin-vsc"
vscode "charliermarsh.ruff"
vscode "dorzey.vscode-sqlfluff"
vscode "editorconfig.editorconfig"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "gleam.gleam"
vscode "jakebecker.elixir-ls"
vscode "kend.dancehelixkey"
vscode "matangover.mypy"
vscode "miguelsolorio.fluent-icons"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "robertostermann.inline-parameters-extended"
vscode "rust-lang.rust-analyzer"
vscode "samuelcolvin.jinjahtml"
vscode "skellock.just"
vscode "subframe7536.custom-ui-style"
vscode "tamasfe.even-better-toml"
vscode "yzhang.markdown-all-in-one"
