config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

dotfiles:
  f_starship:
    dst: ~/.config/starship.toml
    src: starship.toml

  f_ipython:
    dst: ~/.ipython/profile_default/startup/start.py
    src: .ipython/start.py

  f_bat:
    dst: ~/.config/bat/config
    src: bat/config

  f_vim:
    dst: ~/.vimrc
    src: .vimrc

  f_tmux:
    dst: ~/.tmux.conf
    src: .tmux.conf

  f_zsh:
    dst: ~/.zshrc
    src: .zshrc

  f_p10k:
    dst: ~/.p10k.zsh
    src: .p10k.zsh

  d_helix:
    dst: ~/.config/helix
    src: helix
  
  d_btop:
    dst: ~/.config/btop
    src: btop

profiles:
  base:
    dotfiles:
      - f_starship
      - f_ipython
      - f_bat
      - f_vim
      - f_zsh
      - f_p10k
      - f_tmux
      - d_helix
      - d_btop
