config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

dotfiles:
  f_starship:
    dst: ~/.config/starship.toml
    src: starship.toml

  f_ipython:
    dst: ~/.ipython/profile_default/startup/start.py
    src: .ipython/start.py

  f_bat:
    dst: ~/.config/bat/config
    src: bat/config

  f_vim:
    dst: ~/.vimrc
    src: .vimrc

  d_helix:
    dst: ~/.config/helix
    src: helix
  
  d_btop:
    dst: ~/.config/btop
    src: btop

profiles:
  base:
    dotfiles:
      - f_starship
      - f_ipython
      - f_bat
      - f_vim
      - d_helix
      - d_btop
