config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

dotfiles:
  f_starship:
    dst: ~/.config/starship.toml
    src: .config/starship.toml

  f_ipython:
    dst: ~/.ipython/profile_default/startup/start.py
    src: .ipython/profile_default/startup/start.py

  f_bat:
    dst: ~/.config/bat/config
    src: .config/bat/config

  f_vim:
    dst: ~/.vimrc
    src: .vimrc

  f_tmux:
    dst: ~/.tmux.conf
    src: .tmux.conf

  f_zsh:
    dst: ~/.zshrc
    src: .zshrc

  f_hyper_js:
    dst: ~/.hyper.js
    src: .hyper.js

  f_git:
    dst: ~/.gitconfig
    src: .gitconfig

  d_atuin:
    dst: ~/.config/atuin
    src: .config/atuin

  d_helix:
    dst: ~/.config/helix
    src: .config/helix

  d_btop:
    dst: ~/.config/btop
    src: .config/btop

  d_fastfetch:
    dst: ~/.config/fastfetch
    src: .config/fastfetch

  d_xplr:
    dst: ~/.config/xplr
    src: .config/xplr

  d_karabiner:
    dst: ~/.config/karabiner
    src: .config/karabiner

profiles:
  base:
    dotfiles:
      - f_starship
      - f_ipython
      - f_bat
      - f_vim
      - f_zsh
      - f_git
      - f_tmux
      - f_hyper_js
      - d_atuin
      - d_helix
      - d_btop
      - d_fastfetch
      - d_xplr
      - d_karabiner
