config:
  # create a backup of the existing destination
  backup: true
  # do not display the `dotdrop` banner
  banner: false
  # create a directory hierarchy when installing dotfiles if it doesn't exist
  create: true
  # path to the directory containing the dotfiles to be managed by `dotdrop`
  dotpath: dotfiles
  # preserve leading dot when importing hidden file in the `dotpath`
  keepdot: false
  # do not link files and copy them instead
  link_dotfile_default: nolink
  link_on_import: nolink
  # use long keys for dotfiles when importing
  longkey: false
  # execute the next actions for any dotfile installation
  default_actions:
    - bat
    - fzh

actions:
  post:
    # compile `bat` themes
    bat: bat cache --build
    # set theme for`fast-syntax-highlighting`
    fzh: zsh -ic "fast-theme XDG:themes/catppuccin_macchiato"
    # set wallpapers
    wallpapers: osascript -e 'tell application "System Events" to set picture of every desktop to "~/.config/wallpapers/logo/logo_2.png"'

dotfiles:
  # =================================================
  # ~/
  # =================================================

  f_ssh:
    dst: ~/.ssh/config
    src: .ssh/config
  f_gitconfig:
    dst: ~/.gitconfig
    src: .gitconfig
  f_zplugrc:
    dst: ~/.zplugrc
    src: .zplugrc
  f_zshenv:
    dst: ~/.zshenv
    src: .zshenv
  f_zshrc:
    dst: ~/.zshrc
    src: .zshrc

  # =================================================
  # ~/.config
  # =================================================

  d_aerospace:
    dst: ~/.config/aerospace
    src: .config/aerospace
  d_stylus:
    dst: ~/.config/stylus
    src: .config/stylus
  d_wallpapers:
    dst: ~/.config/wallpapers
    src: ../wallpapers
  f_zed:
    dst: ~/.config/zed/settings.json
    src: .config/zed/settings.json

  # =================================================
  # ~/Library/Application Support
  # =================================================

  d_espanso:
    dst: ~/Library/Application Support/espanso
    src: espanso
  d_pypoetry:
    dst: ~/Library/Application Support/pypoetry
    src: pypoetry

profiles:
  home:
    dotfiles:
      - d_aerospace
      - d_espanso
      - d_pypoetry
      - d_stylus
      - d_wallpapers
      - f_gitconfig
      - f_zed
      - f_zplugrc
      - f_zshenv
      - f_zshrc
      - f_ssh
