config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

dotfiles:
  f_starship:
    dst: ~/.config/starship.toml
    src: .config/starship.toml

  f_ipython:
    dst: ~/.ipython/profile_default/startup/start.py
    src: .ipython/profile_default/startup/start.py

  f_zsh:
    dst: ~/.zshrc
    src: .zshrc

  f_git:
    dst: ~/.gitconfig
    src: .gitconfig

  f_lfp:
    dst: ~/.local/bin/lf-pick
    src: .local/bin/lf-pick

  d_yabai:
    dst: ~/.config/yabai/yabairc
    src: .config/yabai/yabairc

  d_skhd:
    dst: ~/.config/skhd/skhdrc
    src: .config/skhd/skhdrc

  d_atuin:
    dst: ~/.config/atuin
    src: .config/atuin

  d_helix:
    dst: ~/.config/helix
    src: .config/helix

  d_bat:
    dst: ~/.config/bat
    src: .config/bat

  d_btop:
    dst: ~/.config/btop
    src: .config/btop

  d_direnv:
    dst: ~/.config/direnv
    src: .config/direnv

  d_xplr:
    dst: ~/.config/xplr
    src: .config/xplr

  d_yazi:
    dst: ~/.config/yazi
    src: .config/yazi

  d_k9s:
    dst: ~/.config/k9s
    src: .config/k9s

  d_warp:
    dst: ~/.warp
    src: .warp

  d_spotify_tui:
    dst: ~/.config/spotify-tui
    src: .config/spotify-tui

  d_spicetify:
    dst: ~/.config/spicetify
    src: .config/spicetify

  d_fleet:
    dst: ~/.fleet
    src: .fleet

  d_qbit:
    dst: ~/.config/qBittorrent
    src: .config/qBittorrent

  d_lazygit:
    dst: ~/.config/lazygit
    src: .config/lazygit

  d_neofetch:
    dst: ~/.config/neofetch
    src: .config/neofetch

  d_lf:
    dst: ~/.config/lf
    src: .config/lf

  d_zellij:
    dst: ~/.config/zellij
    src: .config/zellij

  d_zellij_plugins:
    dst: ~/zellij-plugins
    src: zellij-plugins

profiles:
  base:
    dotfiles:
      - d_atuin
      - d_bat
      - d_btop
      - d_fleet
      - d_helix
      - d_k9s
      - d_lf
      - d_lazygit
      - d_neofetch
      - d_qbit
      - d_skhd
      - d_spicetify
      - d_spotify_tui
      - d_warp
      - d_xplr
      - d_yazi
      - d_yabai
      - d_zellij
      - d_zellij_plugins
      - f_git
      - f_ipython
      - f_starship
      - f_lfp
      - f_zsh
