config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false

dotfiles:
  f_starship:
    dst: ~/.config/starship.toml
    src: .config/starship.toml

  f_ipython:
    dst: ~/.ipython/profile_default/startup/start.py
    src: .ipython/profile_default/startup/start.py

  f_vim:
    dst: ~/.vimrc
    src: .vimrc

  f_tmux:
    dst: ~/.tmux.conf
    src: .tmux.conf

  f_zsh:
    dst: ~/.zshrc
    src: .zshrc

  f_hyper_js:
    dst: ~/.hyper.js
    src: .hyper.js

  f_git:
    dst: ~/.gitconfig
    src: .gitconfig

  f_yabai:
    dst: ~/.config/yabai/yabairc
    src: .config/yabai/yabairc

  f_skhd:
    dst: ~/.config/skhd/skhdrc
    src: .config/skhd/skhdrc

  d_atuin:
    dst: ~/.config/atuin
    src: .config/atuin

  d_helix:
    dst: ~/.config/helix
    src: .config/helix

  d_bat:
    dst: ~/.config/bat
    src: .config/bat

  d_btop:
    dst: ~/.config/btop
    src: .config/btop

  d_fastfetch:
    dst: ~/.config/fastfetch
    src: .config/fastfetch

  d_xplr:
    dst: ~/.config/xplr
    src: .config/xplr

  d_karabiner:
    dst: ~/.config/karabiner
    src: .config/karabiner

  d_k9s:
    dst: ~/.config/k9s
    src: .config/k9s

  d_mc:
    dst: ~/.config/mc
    src: .config/mc

  d_mc_skins:
    dst: ~/.local/share/mc/skins
    src: .local/share/mc/skins

  d_warp:
    dst: ~/.warp
    src: .warp

  d_spotify_tui:
    dst: ~/.config/spotify-tui
    src: .config/spotify-tui

  d_spicetify:
    dst: ~/.config/spicetify
    src: .config/spicetify

  d_fleet:
    dst: ~/.fleet
    src: .fleet

  d_qbit:
    dst: ~/.config/qBittorrent
    src: .config/qBittorrent

  d_nvim:
    dst: ~/.config/nvim
    src: .config/nvim

profiles:
  base:
    dotfiles:
      - f_starship
      - f_ipython
      - f_vim
      - f_zsh
      - f_git
      - f_tmux
      - f_hyper_js
      - f_yabai
      - f_skhd
      - d_atuin
      - d_helix
      - d_bat
      - d_btop
      - d_fastfetch
      - d_xplr
      - d_karabiner
      - d_k9s
      - d_mc
      - d_mc_skins
      - d_warp
      - d_spotify_tui
      - d_spicetify
      - d_fleet
      - d_qbit
      - d_nvim
