- name: Tooling
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Install CLI tools via cargo
      community.general.cargo:
        name: "{{ item }}"
      with_items:
        - gh-xplr  # explore GitHub repos using xplr via GitHub CLI
        - zellij  # pluggable terminal workspace, with terminal multiplexer as the base feature

    - name: Install CLI tools via npm
      community.general.npm:
        name: "{{ item }}"
        global: true
      with_items:
        - git-labelmaker  # edit GitHub labels from the command line

    - name: Install oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      ignore_errors: true


    - name: Install LSPs via npm
      community.general.npm:
        name: "{{ item }}"
        global: true
      with_items:
        - bash-language-server  # bash language server that brings an IDE-like experience for bash scripts to most editors
        - dockerfile-language-server-nodejs  # a language server for Dockerfiles powered by Node.js
        - editorconfig-checker  # tool to verify that your files are in harmony with your .editorconfig
        - graphql-language-service-cli  # interface for building GraphQL language services for IDEs
        - graphql-language-service-server  # interface for building GraphQL language services for IDEs
        - graphql-schema-linter  #  a command line tool to validate GraphQL schema definitions
        - lua-language-server  # Lua language server
        - vscode-langservers-extracted  # HTML/CSS/JSON/ESLint language servers
        - vscode-json-languageservice  # JSON language service extracted from VSCode to be reused
        - yaml-language-server@next  # language server for YAML Files

    - name: Install LSPs via cargo
      community.general.cargo:
        name: "{{ item }}"
      with_items:
        - taplo-cli  # TOML toolkit written in Rust
