# general
background = '#eff1f5'
border_fg = '#bcc0cc'
text_fg = '#4c4f69'
dimmed_text_fg = '#9ca0b0'
# input
input_text_fg = '#8839ef'
result_count_fg = '#8839ef'
# results
result_name_fg = '#1e66f5'
result_line_number_fg = '#df8e1d'
result_value_fg = '#7287fd'
selection_bg = '#ccd0da'
match_fg = '#40a02b'
# preview
preview_title_fg = '#8839ef'
# modes
channel_mode_fg = '#8839ef'
remote_control_mode_fg = '#40a02b'
send_to_channel_mode_fg = '#04a5e5'
