"$schema" = 'https://starship.rs/config-schema.json'

palette = "morok"

[palettes.morok]
rosewater = "#e2cfc6"
flamingo = "#d8b8aa"
pink = "#d1b2c9"
mauve = "#a78cc4"
red = "#c98787"
maroon = "#b97a74"
peach = "#d0a178"
yellow = "#c7b07a"
green = "#8ea98c"
teal = "#7ea59d"
sky = "#7da2b5"
sapphire = "#7398ad"
blue = "#7f98bf"
lavender = "#9faece"
text = "#e7e5e4"
subtext1 = "#d6d3d1"
subtext0 = "#a8a29e"
overlay2 = "#a8a29e"
overlay1 = "#78716c"
overlay0 = "#57534e"
surface2 = "#44403c"
surface1 = "#292524"
surface0 = "#1c1917"
base = "#000000"
mantle = "#0c0a09"
crust = "#080706"

[aws]
symbol = "󰸏 "
force_display = false

[azure]
symbol = " "
disabled = false

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[❯](bold blue)"
vimcmd_symbol = "[❮](bold blue)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = "  "
truncation_length = 4
style = "bold blue"

[docker_context]
symbol = "󰡨 "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "󰊢 "
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
deleted = "✘ "

[golang]
symbol = " "

[gleam]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_only = true
ssh_symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "
disabled = false

[lua]
symbol = "󰢱 "

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[nodejs]
symbol = "󰎙 "

[openstack]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "green bold"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
fish_indicator = ""
style = "lavender bold"
disabled = false

[status]
symbol = " "
success_symbol = ""
not_executable_symbol = " "
map_symbol = false
disabled = false

[swift]
symbol = " "

[terraform]
symbol = "󱁢 "
