"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

[aws]
symbol = "󰸏 "
force_display = false

[azure]
symbol = " "
disabled = false

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = "󰡨 "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "󰊢 "
tag_disabled = false

[git_metrics]
disabled = false

[golang]
symbol = " "

[gleam]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_only = true
ssh_symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = "󱃾 "
disabled = false

[lua]
symbol = "󰢱 "

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[nodejs]
symbol = "󰎙 "

[openstack]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "green bold"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
zsh_indicator = "󰊠"
style = "green bold"
disabled = false

[status]
symbol = " "
success_symbol = ""
not_executable_symbol = " "
map_symbol = false
disabled = false

[swift]
symbol = " "

[terraform]
symbol = "󱁢 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
