version: 2
root-markers:
  - .git/
  - .svn/
  - pyproject.toml
  - Cargo.toml

tools:
  codespell: &codespell
    lint-command: 'codespell'
    lint-formats:
      - '%f:%l: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  python:
    - <<: *codespell
    - <<: *python-mypy
