cversion: 2
lint-debounce: 1s
root-markers:
  - .git/
  - .github/
  - Cargo.toml
  - package.json
  - pyproject.toml

tools:
  codespell: &codespell
    prefix: codespell
    lint-command: "codespell"
    lint-formats:
      - "%f:%l: %m"
    root-markers:
      - pyproject.toml

  bash-shfmt: &bash-shfmt
    format-command: "shfmt -ci -s -bn"
    format-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: "hadolint --no-color"
    lint-formats:
      - "%f:%l DL%n %tnfo: %m"
      - "%f:%l DL%n %tarning: %m"
      - "%f:%l DL%n %trror: %m"

  env-dotenv-linter: &env-dotenv-linter
    lint-command: "dotenv-linter --no-color --not-check-updates -q"
    lint-formats:
      - "%f:%l %m"

  git-commit-gitlint: &git-commit-gitlint
    lint-command: "gitlint --ignore B6"
    lint-stdin: true
    lint-formats:
      - '%l: %m: "%r"'
      - "%l: %m"

  git-commit-commitizen: &git-commit-commitizen
    lint-command: "cz check --commit-msg-file"
    lint-formats:
      - "%m"

  yaml-actionlint: &yaml-actionlint
    prefix: actionlint
    lint-command: "zsh -c \"[[ '${INPUT}' =~ \\\\.github/workflows/ ]]\" && actionlint -oneline -no-color -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    root-markers:
      - .github

  yaml-ansible-lint: &yaml-ansible-lint
    lint-command: "ansible-lint -f pep8 -q"
    lint-formats:
      - "%f:%l: %m"
    root-markers:
      - .ansible-lint

  yaml-yamllint: &yaml-yamllint
    prefix: yamllint
    lint-command: "yamllint --strict --format parsable ${INPUT}"
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: [%t%*[a-z]] %m"
    env:
      - "PYTHONIOENCODING=UTF-8"

  yaml-yamlfmt: &yaml-yamlfmt
    prefix: yamlfmt
    format-command: "yamlfmt -in"
    format-stdin: true

languages:
  =:
    - <<: *codespell

  bash:
    - <<: *bash-shfmt

  dockerfile:
    - <<: *dockerfile-hadolint

  env:
    - <<: *env-dotenv-linter

  git-commit:
    - <<: *git-commit-gitlint
    - <<: *git-commit-commitizen

  yaml:
    - <<: *yaml-actionlint
    - <<: *yaml-ansible-lint
    - <<: *yaml-yamllint
    - <<: *yaml-yamlfmt
