palette = 0=#292524
palette = 1=#c98787
palette = 2=#8ea98c
palette = 3=#c7b07a
palette = 4=#7f98bf
palette = 5=#d1b2c9
palette = 6=#7ea59d
palette = 7=#a8a29e
palette = 8=#44403c
palette = 9=#c98787
palette = 10=#8ea98c
palette = 11=#c7b07a
palette = 12=#7f98bf
palette = 13=#d1b2c9
palette = 14=#7ea59d
palette = 15=#d6d3d1
background = #000000
foreground = #e7e5e4
cursor-color = #e2cfc6
cursor-text = #080706
selection-background = #5c5957
selection-foreground = #e7e5e4
split-divider-color = #1c1917
