# =============================================================================================
# Taps
# =============================================================================================

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"

# =============================================================================================
# Fonts
# =============================================================================================

cask "font-jetbrains-mono"
cask "font-symbols-only-nerd-font"

# =============================================================================================
# Apps
# =============================================================================================

# memory training application
cask "anki"
# installer for betterdiscord
cask "betterdiscord-installer"
# universal database tool and SQL client
cask "dbeaver-community"
# voice and text chat software
cask "discord"
# web browser focusing on privacy
cask "duckduckgo"
# screen colour temperature controller
cask "flux"
# web browser
cask "google-chrome"
# terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# HTTP and GraphQL Client
cask "insomnia"
# jetbrains tools manager
cask "jetbrains-toolbox"
# keyboard customiser
cask "karabiner-elements"
# file archiver
cask "keka"
# logitech options+
cask "logi-options-plus"
# password manager
cask "nordpass"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# peer to peer torrent client
cask "qbittorrent"
# custom spotlight
cask "raycast"
# team communication and collaboration software
cask "slack"
# quicklook extension for source files
cask "syntax-highlight"
# music streaming service
cask "spotify"
# messaging app with a focus on speed and security
cask "telegram"
# open-source code editor
cask "visual-studio-code"

# the cat tells you the CPU usage of Mac by running speed
# mas "RunCat", id: 1429033973
# pomodoro timer
# mas "Flow", id: 1423210932

# =============================================================================================
# QuickLook plugins
# =============================================================================================

cask "qlmarkdown"

# =============================================================================================
# Programming languages, REPLs
# =============================================================================================

# programming language for highly scalable real-time systems
brew "erlang"
# functional metaprogramming aware language built on Erlang VM
brew "elixir"
# statically typed language for the Erlang VM
brew "gleam"
# powerful, lightweight programming language
brew "lua"
# platform built on V8 to build network applications
brew "node"
# powerful, clean, object-oriented scripting language
brew "ruby"

# =============================================================================================
# CLI tools
# =============================================================================================

# runs GitHub Actions locally
brew "act"
# cat with syntax highlighting and Git integration
brew "bat"
# yet another cross-platform graphical process/system monitor
brew "bottom"
# defines a standard way of committing rules
brew "commitizen"
# query HTTP, HTTPS or FTP server
brew "curl"
# load/unload environment variables based on $PWD
brew "direnv"
# dotfiles manager
brew "dotdrop"
# pack, ship and run any application as a lightweight container
brew "docker"
# clean Docker containers, images, networks, and volumes
brew "docker-clean"
# CLI tool for running SQL queries against JSON, CSV, Excel, Parquet
brew "dsq"
# embeddable SQL OLAP Database Management System
brew "duckdb"
# modern replacement for 'ls'
brew "exa"
# simple, fast and user-friendly alternative to find
brew "fd"
# command-line fuzzy finder written in go
brew "fzf"
# gnu compiler collection
brew "gcc"
# github command-line tool
brew "gh"
# syntax-highlighting pager for git and diff output
brew "git-delta"
# graph visualization software from at&t and bell labs
brew "graphviz"
# post-modern modal text editor
brew "helix"
# lightweight and flexible command-line json processor
brew "jq"
# kubernetes cli to manage your clusters in style!
brew "k9s"
# hotkey daemon for macOS
brew "koekeishiya/formulae/skhd"
# tiling window manager for macOS
brew "koekeishiya/formulae/yabai"
# kubernetes command-line interface
brew "kubernetes-cli"
# lazier way to manage everything docker
brew "lazydocker"
# simple terminal ui for git commands
brew "lazygit"
# interactive cheatsheet tool for the command-line
brew "navi"
# fast, highly customisable system info script
brew "neofetch"
# manage multiple Node.js versions
brew "nvm"
# pinentry for GPG on Mac
brew "pinentry-mac"
# python version management
brew "pyenv"
# pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# search tool like grep and the silver searcher
brew "ripgrep"
# install various Ruby versions and implementations
brew "ruby-build"
# ruby version manager
brew "rbenv"
# rust toolchain installer
brew "rustup-init"
# Spotify for the terminal written in Rust
brew "spotify-tui"
# Spotify customization
brew "spicetify/homebrew-tap/spicetify-cli"
# cross-shell prompt for astronauts
brew "starship"
# display directories as trees (with optional color/html output)
brew "tree"
# command-line unarchiving tools supporting multiple formats
brew "unar"
# your cli home video recorder
brew "vhs"
# internet file retriever
brew "wget"
# shell extension to navigate your filesystem faster
brew "zoxide"
# next-generation plugin manager for zsh
brew "zplug"

# =============================================================================================
# Linters, formatters and LSPs
# =============================================================================================

# static checker for GitHub Actions workflow files
brew "actionlint"
# language server for Ansible files
brew "ansible-lint"
brew "ansible-language-server"
# linter for .env files
brew "dotenv-linter"
# general purpose language server
brew "efm-langserver"
# Language Server and Debugger for Elixir
brew "elixir-ls"
# smarter Dockerfile linter to validate best practices
brew "hadolint"
# LSP for LanguageTool with support for Latex
brew "ltex-ls"
# Language Server Protocol for Markdown
brew "marksman"
# autoformat shell script source code
brew "shfmt"
# modernized, complete, self-contained TeX/LaTeX engine
brew "tectonic"
# implementation of the Language Server Protocol for LaTeX
brew "texlab"
# extensible command-line tool to format YAML files
brew "yamlfmt"

# =============================================================================================
# VSCode extensions
# =============================================================================================

vscode "alefragnani.project-manager"
vscode "catppuccin.catppuccin-vsc"
vscode "charliermarsh.ruff"
vscode "colinfang.my-nbpreviewer"
vscode "donjayamanne.python-environment-manager"
vscode "dorzey.vscode-sqlfluff"
vscode "drcika.apc-extension"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "equinusocio.vsc-material-theme-icons"
vscode "github.vscode-pull-request-github"
vscode "griimick.vhs"
vscode "hbenl.vscode-test-explorer"
vscode "ibrahimfadel.yabai-syntax-highlighting"
vscode "james-yu.latex-workshop"
vscode "kdl-org.kdl"
vscode "knowsuchagency.pdm-task-provider"
vscode "littlefoxteam.vscode-python-test-adapter"
vscode "marclipovsky.string-manipulation"
vscode "matangover.mypy"
vscode "miguelsolorio.fluent-icons"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.test-adapter-converter"
vscode "naumovs.color-highlight"
vscode "njpwerner.autodocstring"
vscode "oderwat.indent-rainbow"
vscode "peterschmalfeldt.explorer-exclude"
vscode "ritwickdey.liveserver"
vscode "robertostermann.inline-parameters-extended"
vscode "rodolphebarbanneau.python-docstring-highlighter"
vscode "rust-lang.rust-analyzer"
vscode "samuelcolvin.jinjahtml"
vscode "serayuzgur.crates"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "silverquark.dancehelix"
vscode "swellaby.vscode-rust-test-adapter"
vscode "tamasfe.even-better-toml"
vscode "tgriesser.avro-schemas"
vscode "tonybaloney.python-task-provider"
vscode "trond-snekvik.simple-rst"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "visualstudioexptteam.vscodeintellicode-completions"
vscode "vspacecode.whichkey"
vscode "wakatime.vscode-wakatime"
vscode "yzhang.markdown-all-in-one"
vscode "zeshuaro.vscode-python-poetry"
