theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "always"
shell = ["zsh", "-c"]
true-color = true
color-modes = true
cursorline = true
mouse = true
rulers = [100]
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = [
  "mode",
  "separator",
  "version-control",
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
]
center = []
right = [
  "selections",
  "primary-selection-length",
  "position",
  "spacer",
  "total-line-numbers",
  "file-name",
  "file-type",
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
