theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "always"
shell = ["zsh", "-c"]
true-color = true
color-modes = true
cursorline = true
mouse = true
rulers = [100]
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control"
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-f = [
    ":new",
    ":insert-output lf-pick",
    ":theme default",
    "select_all",
    "split_selection_on_newline",
    "goto_file",
    "goto_last_modified_file",
    ":buffer-close!",
    ":theme catppuccin_macchiato"
]
