# =================================================
# Theme
# =================================================

theme = "catppuccin_macchiato"

# =================================================
# Editor
# =================================================

[editor]
bufferline = "always"
color-modes = true
completion-trigger-len = 1
cursorline = true
# minimum severity to show a diagnostic after the end of a line
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = true
rulers = [100]
shell = ["zsh", "-c"]
true-color = true

[editor.inline-diagnostics]
# show a diagnostic on the primary cursor's line
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = false
hidden = false
ignore = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
center = []
left = [
  "mode",
  "separator",
  "version-control",
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
]
right = [
  "selections",
  "primary-selection-length",
  "position",
  "spacer",
  "total-line-numbers",
  "file-name",
  "file-type",
]
separator = "│"

[editor.whitespace.render]
newline = "none"
space = "all"
tab = "all"

[editor.whitespace.characters]
nbsp = "⍽"
space = "·"
tab = "→"
tabpad = "·"
