theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
shell = ["zsh", "-c"]
true-color = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
    "diagnostics",
    "selections",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type",
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
