theme = "catppuccin_macchiato"

[editor]
bufferline = "always"
color-modes = true
completion-trigger-len = 1
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = true
rulers = [100]
shell = ["zsh", "-c"]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = true
hidden = false
ignore = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
center = []
left = ["mode", "separator", "version-control", "spinner", "diagnostics", "workspace-diagnostics"]
right = ["selections", "primary-selection-length", "position", "spacer", "total-line-numbers", "file-name", "file-type"]
separator = "│"

[editor.whitespace.characters]
nbsp = "⍽"
space = "·"
tab = "→"
tabpad = "·"

[editor.whitespace.render]
newline = "none"
space = "all"
tab = "all"
