matches:

# =============================================================================================
# Emojis
# =============================================================================================

  - trigger: ":nya"
    replace: :3

  - trigger: ":ees"
    replace: "🙂"

  - trigger: ":eec"
    replace: 🥲

  - trigger: ":eet"
    replace: "🤔"

# =============================================================================================
# git commit
# =============================================================================================

  - trigger: ":gcbuildu"
    form: "build([[tool]]): update dependencies"
    form_fields:
      tool:
        default: poetry

  - trigger: ":gcbuilda"
    form: "build([[tool]]): add `[[dependency]]`"
    form_fields:
      tool:
        default: poetry

  - trigger: ":gcbuildr"
    form: "build([[tool]]): remove `[[dependency]]`"
    form_fields:
      tool:
        default: poetry

  - trigger: ":gcsf"
    form: "style([[component]]): run formatters"

  - trigger: ":gcgsf"
    form: "style: run formatters"

  - trigger: ":gchooksu"
    replace: "ci(pre-commit): update hooks"

  - trigger: ":gchooksa"
    form: "ci(pre-commit): add `[[hook]]`"

  - trigger: ":gchooksr"
    form: "ci(pre-commit): remove `[[hook]]`"

# =============================================================================================
# git commands
# =============================================================================================

  - trigger: ":gr"
    replace: "git rebase -i HEAD~10"

# =============================================================================================
# Misc
# =============================================================================================

  # print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

