matches:
  - trigger: ":date"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y%m%d"

  # =================================================
  # git commits
  # =================================================

  - trigger: ":gcbldu"
    form: "build: update dependencies"

  - trigger: ":gcblda"
    form: "build: add [[dependency]]"

  - trigger: ":gcbldar"
    form: "build: remove [[dependency]]"

  - trigger: ":gcsf"
    form: "style: run formatters"

  - trigger: ":gcrl"
    form: "refactor: run linters"
