# == Core ==
alias cat="bat"
alias find="fd"
alias grep="rg"
alias ls="eza --all --icons=always"

# == Docker ==
alias d="docker"
alias dco="docker compose"
alias dl="docker ps -l -q"
alias dpa="docker ps -a"
alias dps="docker ps"
alias dx="docker exec -it"

# == External tools ==
alias ld="lazydocker"
alias lg="lazygit"
alias zj="zellij"

# == Git ==
alias g="git"
alias ga="git add"
alias gb="git branch"
alias gba="git branch -a"
alias gc="git commit -m"
alias gca="git commit -a --amend"
alias gd="git diff"
alias gp="git push origin HEAD"
alias gpu="git pull origin"
alias gr="git reset"
alias gri="git rebase -i"
alias grir="git rebase -i --root"
alias gs="git switch"
alias gst="git status"
alias gu="git reset HEAD~1 --mixed"

# == Helm ==
alias h="helm"
alias hd="helm delete"
alias hdep="helm dependency"
alias hdeps="helm dependency update"
alias hg="helm get"
alias hga="helm get all"
alias hgm="helm get manifest"
alias hgv="helm get values"
alias hi="helm install"
alias hl="helm list"
alias hla="helm list --all"
alias hp="helm package"
alias hr="helm repo"
alias hra="helm repo add"
alias hrl="helm repo list"
alias hrr="helm repo remove"
alias hru="helm repo update"
alias hs="helm search"
alias hsh="helm show"
alias hsha="helm show all"
alias hshc="helm show chart"
alias hshv="helm show values"
alias hst="helm status"
alias ht="helm template"
alias hug="helm upgrade"
alias hui="helm upgrade --install"
alias hun="helm uninstall"

# == Kubernetes ==
alias k="kubectl"
alias ka="kubectl apply -f"
alias kb="kubectl describe"
alias kc="kubectx"
alias kcns="kubectl config set-context --current --namespace"
alias kd="kubectl describe"
alias kdel="kubectl delete"
alias ke="kubectl exec -it"
alias kg="kubectl get"
alias kgd="kubectl get deployments"
alias kgpo="kubectl get pod"
alias kl="kubectl logs"
alias klf="kubectl logs -f"
alias kns="kubens"

# == UV ==
alias u="uv"
alias uva="uv add"
alias uvl="uv lock"
alias uvr="uv run"
alias uvs="uv sync -U --all-groups --all-extras"
alias uvv="uv venv"
