[styles.cpu]
all_entry_color = "#e2cfc6"
avg_entry_color = "#b97a74"
cpu_core_colors = ["#c98787", "#d0a178", "#c7b07a", "#8ea98c", "#7398ad", "#a78cc4"]

[styles.memory]
ram_color = "#8ea98c"
cache_color = "#c98787"
swap_color = "#d0a178"
gpu_colors = ["#7398ad", "#a78cc4", "#c98787", "#d0a178", "#c7b07a", "#8ea98c"]
arc_color = "#7da2b5"

[styles.network]
rx_color = "#8ea98c"
tx_color = "#c98787"
rx_total_color = "#7da2b5"
tx_total_color = "#8ea98c"

[styles.battery]
high_battery_color = "#8ea98c"
medium_battery_color = "#c7b07a"
low_battery_color = "#c98787"

[styles.tables]
headers = { color = "#e2cfc6" }

[styles.graphs]
graph_color = "#a8a29e"
legend_text = { color = "#a8a29e" }

[styles.widgets]
border_color = "#44403c"
selected_border_color = "#d1b2c9"
widget_title = { color = "#d8b8aa" }
text = { color = "#e7e5e4" }
selected_text = { color = "#080706", bg_color = "#a78cc4" }
disabled_text = { color = "#000000" }
