# Syntax highlighting
# -------------------
"attribute" = "yellow"

"type" = "yellow"
"type.builtin" = "mauve"
"type.enum.variant" = "teal"

"constructor" = "sapphire"

"constant" = "peach"
"constant.character" = "teal"
"constant.character.escape" = "pink"

"string" = "green"
"string.regexp" = "pink"
"string.special" = "blue"
"string.special.symbol" = "red"

"comment" = { fg = "overlay2", modifiers = ["italic"] }

"variable" = "text"
"variable.parameter" = { fg = "maroon", modifiers = ["italic"] }
"variable.builtin" = "red"
"variable.other.member" = "blue"

"label" = "sapphire"

"punctuation" = "overlay2"
"punctuation.special" = "sky"

"keyword" = "mauve"
"keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }

"operator" = "sky"

"function" = "blue"
"function.macro" = "rosewater"

"tag" = "blue"

"namespace" = { fg = "yellow", modifiers = ["italic"] }

"special" = "blue"

"markup.heading.1" = "red"
"markup.heading.2" = "peach"
"markup.heading.3" = "yellow"
"markup.heading.4" = "green"
"markup.heading.5" = "sapphire"
"markup.heading.6" = "lavender"
"markup.list" = "teal"
"markup.list.unchecked" = "overlay2"
"markup.list.checked" = "green"
"markup.bold" = { fg = "red", modifiers = ["bold"] }
"markup.italic" = { fg = "red", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.link.text" = "lavender"
"markup.link.label" = "sapphire"
"markup.raw" = "green"
"markup.quote" = "pink"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"

# User Interface
# --------------
"ui.background" = { fg = "text", bg = "base" }

"ui.linenr" = { fg = "surface1" }
"ui.linenr.selected" = { fg = "lavender" }

"ui.statusline" = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive" = { fg = "surface2", bg = "mantle" }
"ui.statusline.normal" = { fg = "base", bg = "rosewater", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "base", bg = "lavender", modifiers = ["bold"] }

"ui.popup" = { fg = "text", bg = "surface0" }
"ui.window" = { fg = "crust" }
"ui.help" = { fg = "overlay2", bg = "surface0" }

"ui.bufferline" = { fg = "subtext0", bg = "mantle" }
"ui.bufferline.active" = { fg = "mauve", bg = "base", underline = { color = "mauve", style = "line" } }
"ui.bufferline.background" = { bg = "crust" }

"ui.text" = "text"
"ui.text.focus" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "overlay1" }
"ui.text.directory" = { fg = "blue" }

"ui.virtual" = "overlay0"
"ui.virtual.ruler" = { bg = "surface0" }
"ui.virtual.indent-guide" = "surface0"
"ui.virtual.inlay-hint" = { fg = "surface1", bg = "mantle" }
"ui.virtual.jump-label" = { fg = "rosewater", modifiers = ["bold"] }

"ui.selection" = { bg = "surface1" }

"ui.cursor" = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.primary" = { fg = "base", bg = "rosewater" }
"ui.cursor.match" = { fg = "peach", modifiers = ["bold"] }

"ui.cursor.primary.normal" = { fg = "base", bg = "rosewater" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "lavender" }

"ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.select" = { fg = "base", bg = "secondary_cursor_select" }

"ui.cursorline.primary" = { bg = "cursorline" }

"ui.highlight" = { bg = "surface1", modifiers = ["bold"] }

"ui.menu" = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected" = { fg = "text", bg = "surface1", modifiers = ["bold"] }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"

rainbow = ["red", "peach", "yellow", "green", "sapphire", "lavender"]

[palette]
rosewater = "#e2cfc6"
flamingo = "#d8b8aa"
pink = "#d1b2c9"
mauve = "#a78cc4"
red = "#c98787"
maroon = "#b97a74"
peach = "#d0a178"
yellow = "#c7b07a"
green = "#8ea98c"
teal = "#7ea59d"
sky = "#7da2b5"
sapphire = "#7398ad"
blue = "#7f98bf"
lavender = "#9faece"
text = "#e7e5e4"
subtext1 = "#d6d3d1"
subtext0 = "#a8a29e"
overlay2 = "#a8a29e"
overlay1 = "#78716c"
overlay0 = "#57534e"
surface2 = "#44403c"
surface1 = "#292524"
surface0 = "#1c1917"
base = "#000000"
mantle = "#0c0a09"
crust = "#080706"

cursorline = "#12100f"
secondary_cursor = "#9e918b"
secondary_cursor_select = "#6f7a90"
secondary_cursor_normal = "#9e918b"
secondary_cursor_insert = "#637662"
