[morok]
# Spicetify
text = e7e5e4
subtext = e7e5e4
main = 000000
main-elevated = 1c1917
highlight = 211d1c
highlight-elevated = 292524
sidebar = 0c0a09
player = 080706
card = 1c1917
shadow = 0c0a09
selected-row = a8a29e
button = 78716c
button-active = a8a29e
button-disabled = 57534e
tab-active = 1c1917
notification = 1c1917
notification-error = c98787
equalizer = 000000
misc = 292524

crust = 080706
mantle = 0c0a09
base = 000000
surface0 = 1c1917
surface1 = 292524
surface2 = 44403c
overlay0 = 57534e
overlay1 = 78716c
overlay2 = a8a29e
rosewater = e2cfc6
flamingo = d8b8aa
pink = d1b2c9
maroon = b97a74
red = c98787
peach = d0a178
yellow = c7b07a
green = 8ea98c
teal = 7ea59d
sapphire = 7398ad
blue = 7f98bf
sky = 7da2b5
mauve = a78cc4
lavender = 9faece
