[tool.poetry]
name = "poetry-instance"
version = "1.7.1"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.11.6"
poetry = ">=1.8.1"

[tool.poetry.group.additional.dependencies]
poethepoet = ">=0.25.0"
poetry-plugin-dotenv = ">=0.6.10"
poetry-plugin-up = ">=0.7.1"
