- name: Dependencies
  hosts: localhost
  vars:
    ansible_connection: local

  tasks:
    - name: homebrew
      tags: homebrew
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          brew bundle --file "../dependencies/Brewfile"

    - name: pip
      tags: pip
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          brew bundle --file "../dependencies/requirements.txt"

    - name: cargo
      tags: cargo
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          grep -v "^#" "../dependencies/cargo.txt" | xargs cargo install

    - name: npm
      tags: npm
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          grep -v "^#" "../dependencies/npm.txt" | xargs npm install -g
